services:
  - type: web
    name: whatsapp-agent
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DASHBOARD_PORT
        value: 10000
      - key: ADMIN_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
    healthCheckPath: /health
    autoDeploy: true
